resources:
- manager.yaml
- priority_classes.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/adebrie/llmkube-controller
  newTag: intel-test-202605021314
