---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - foreman.llmkube.dev
  resources:
  - agentictasks
  - fleetnodes
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - foreman.llmkube.dev
  resources:
  - agentictasks/finalizers
  - fleetnodes/finalizers
  - workloads/finalizers
  verbs:
  - update
- apiGroups:
  - foreman.llmkube.dev
  resources:
  - agentictasks/status
  - fleetnodes/status
  - workloads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inference.llmkube.dev
  resources:
  - inferenceservices
  - modelrouters
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.llmkube.dev
  resources:
  - inferenceservices/finalizers
  - modelrouters/finalizers
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - inference.llmkube.dev
  resources:
  - inferenceservices/status
  - modelrouters/status
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
  - list
  - watch
