## Append samples of your project ##
resources:
- inference_v1alpha1_model.yaml
- inference_v1alpha1_inferenceservice.yaml
- inferenceservice_ephemeral_cache.yaml
- inference_v1alpha1_modelpool.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
