/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package agent

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestIsGeneratedGoFile(t *testing.T) {
	ws := t.TempDir()
	write := func(rel, content string) {
		full := filepath.Join(ws, rel)
		_ = os.MkdirAll(filepath.Dir(full), 0o755)
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("api/zz_generated.deepcopy.go", "package v1\n")
	write("pkg/x/thing.pb.go", "package x\n")
	write("pkg/x/gen.go", "// Code generated by foo. DO NOT EDIT.\npackage x\n")
	write("pkg/x/hand.go", "package x\n\nfunc F() {}\n")

	cases := map[string]bool{
		"api/zz_generated.deepcopy.go": true,
		"pkg/x/thing.pb.go":            true,
		"pkg/x/gen.go":                 true,
		"pkg/x/hand.go":                false,
	}
	for path, want := range cases {
		if got := isGeneratedGoFile(ws, path); got != want {
			t.Errorf("isGeneratedGoFile(%q)=%v want %v", path, got, want)
		}
	}
}

func TestChangedNonTestGoFiles(t *testing.T) {
	ws := t.TempDir()
	for _, p := range []string{"pkg/x/hand.go", "pkg/x/hand_test.go", "pkg/x/zz_generated.deepcopy.go"} {
		full := filepath.Join(ws, p)
		_ = os.MkdirAll(filepath.Dir(full), 0o755)
		_ = os.WriteFile(full, []byte("package x\n"), 0o644)
	}
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		return " M pkg/x/hand.go\x00 M pkg/x/hand_test.go\x00 M pkg/x/zz_generated.deepcopy.go\x00 M docs/readme.md\x00", nil
	}
	got := changedNonTestGoFiles(context.Background(), ws, runner)
	if len(got) != 1 || got[0] != "pkg/x/hand.go" {
		t.Fatalf("changedNonTestGoFiles = %v, want [pkg/x/hand.go]", got)
	}
}

func TestCheckTestPresence(t *testing.T) {
	ws := t.TempDir()
	full := filepath.Join(ws, "internal/controller/x.go")
	_ = os.MkdirAll(filepath.Dir(full), 0o755)
	_ = os.WriteFile(full, []byte("package controller\n\nfunc waitForIdle() {}\n"), 0o644)

	statusOut := " M internal/controller/x.go\x00"
	diffOut := "diff --git a/internal/controller/x.go b/internal/controller/x.go\n" +
		"@@ -0,0 +1,3 @@\n+package controller\n+\n+func waitForIdle() {}\n"
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		if name == "git" && len(args) > 0 && args[0] == "status" {
			return statusOut, nil
		}
		if name == "git" && len(args) > 0 && args[0] == "diff" {
			return diffOut, nil
		}
		return "", nil
	}

	failed, out := checkTestPresence(context.Background(), ws, runner)
	if !failed {
		t.Fatal("expected presence failure for new func with no test")
	}
	if !strings.Contains(out, "internal/controller") || !strings.Contains(out, "waitForIdle") {
		t.Errorf("feedback should name the package and the new func; got:\n%s", out)
	}
}

// TestCheckTestPresence_PassesWhenTestChanged is updated to reflect the new
// per-symbol requirement: the changed _test.go must reference the added func by
// name (here "New") for the package to pass. The old assertion ("any changed
// _test.go passes") encoded the loosened per-package behavior we are
// deliberately tightening, so we now write the test file's content to disk so
// the per-symbol check can read it and find the reference.
func TestCheckTestPresence_PassesWhenTestChanged(t *testing.T) { //nolint:dupl
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "pkg/x"), 0o755)
	_ = os.WriteFile(filepath.Join(ws, "pkg/x/x.go"), []byte("package x\nfunc New(){}\n"), 0o644)
	// The test file references "New" so the per-symbol check is satisfied.
	_ = os.WriteFile(filepath.Join(ws, "pkg/x/x_test.go"),
		[]byte("package x\nimport \"testing\"\nfunc TestNew(t *testing.T) { New() }\n"), 0o644)
	statusOut := " M pkg/x/x.go\x00 M pkg/x/x_test.go\x00"
	// git diff -- file: plain diff (no -U0 flag) — used by addedFuncNames
	diffOut := "@@ -0,0 +1,1 @@\n+func New() {}\n"
	// git diff -U0 -- file: used by modifiedFuncNames (no hunk-context func here)
	diffU0Out := "@@ -0,0 +1,1 @@\n+func New() {}\n"
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return statusOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 1 && args[1] == "-U0":
			return diffU0Out, nil
		case name == "git" && args[0] == "diff":
			return diffOut, nil
		}
		return "", nil
	}
	failed, _ := checkTestPresence(context.Background(), ws, runner)
	if failed {
		t.Fatal("presence must pass when the package has a changed _test.go referencing New")
	}
}

// TestCheckTestPresence_UnrelatedTestDoesNotExempt verifies that a changed
// _test.go that references only an unrelated symbol (Bar) does not exempt an
// added func (Foo) from the per-symbol presence check.
func TestCheckTestPresence_UnrelatedTestDoesNotExempt(t *testing.T) {
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "internal/controller"), 0o755)
	_ = os.WriteFile(filepath.Join(ws, "internal/controller/x.go"),
		[]byte("package controller\nfunc Foo() {}\n"), 0o644)
	// y_test.go references Bar only — Foo is unreferenced.
	_ = os.WriteFile(filepath.Join(ws, "internal/controller/y_test.go"),
		[]byte("package controller\nfunc TestBar(t interface{}) { _ = Bar }\n"), 0o644)

	statusOut := " M internal/controller/x.go\x00 M internal/controller/y_test.go\x00"
	// git diff -- x.go: plain diff, adds func Foo
	diffOut := "diff --git a/internal/controller/x.go b/internal/controller/x.go\n" +
		"@@ -0,0 +1,2 @@\n+package controller\n+func Foo() {}\n"
	// git diff -U0 -- x.go: -U0 diff, no trailing func context on this hunk
	diffU0Out := "@@ -0,0 +1,2 @@\n+package controller\n+func Foo() {}\n"

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return statusOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 1 && args[1] == "-U0":
			return diffU0Out, nil
		case name == "git" && args[0] == "diff":
			return diffOut, nil
		}
		return "", nil
	}

	failed, out := checkTestPresence(context.Background(), ws, runner)
	if !failed || !strings.Contains(out, "Foo") {
		t.Fatalf("want failure naming Foo, got failed=%v out=%q", failed, out)
	}
}

// TestCheckTestPresence_ReferencingTestPasses verifies that a changed _test.go
// that references the added func Foo by name satisfies the per-symbol check.
func TestCheckTestPresence_ReferencingTestPasses(t *testing.T) { //nolint:dupl
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "pkg/x"), 0o755)
	_ = os.WriteFile(filepath.Join(ws, "pkg/x/x.go"),
		[]byte("package x\nfunc Foo() {}\n"), 0o644)
	// x_test.go references Foo — presence is satisfied.
	_ = os.WriteFile(filepath.Join(ws, "pkg/x/x_test.go"),
		[]byte("package x\nfunc TestFoo(t interface{}) { Foo() }\n"), 0o644)

	statusOut := " M pkg/x/x.go\x00 M pkg/x/x_test.go\x00"
	diffOut := "@@ -0,0 +1,2 @@\n+package x\n+func Foo() {}\n"
	diffU0Out := "@@ -0,0 +1,2 @@\n+package x\n+func Foo() {}\n"

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return statusOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 1 && args[1] == "-U0":
			return diffU0Out, nil
		case name == "git" && args[0] == "diff":
			return diffOut, nil
		}
		return "", nil
	}

	failed, _ := checkTestPresence(context.Background(), ws, runner)
	if failed {
		t.Fatal("a test referencing Foo should satisfy presence")
	}
}

// TestCheckTestPresence_ModifiedFuncNeedsTest verifies that a body-modified
// function (no net-new +func line) is flagged when no changed test references
// it by name.
func TestCheckTestPresence_ModifiedFuncNeedsTest(t *testing.T) {
	ws := t.TempDir()
	_ = os.MkdirAll(filepath.Join(ws, "pkg/diff"), 0o755)
	_ = os.WriteFile(filepath.Join(ws, "pkg/diff/diff.go"),
		[]byte("package diff\nfunc DiffNameOnly() string { return \"new\" }\n"), 0o644)
	// No changed _test.go at all.

	statusOut := " M pkg/diff/diff.go\x00"
	// git diff -- diff.go: body changed but no +func line
	diffOut := "diff --git a/pkg/diff/diff.go b/pkg/diff/diff.go\n" +
		"@@ -1,2 +1,2 @@ func DiffNameOnly() string {\n-\treturn \"old\"\n+\treturn \"new\"\n"
	// git diff -U0 -- diff.go: hunk header carries the enclosing func name
	diffU0Out := "@@ -1,1 +1,1 @@ func DiffNameOnly() string {\n-\treturn \"old\"\n+\treturn \"new\"\n"

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return statusOut, nil
		case name == "git" && args[0] == "diff" && len(args) > 1 && args[1] == "-U0":
			return diffU0Out, nil
		case name == "git" && args[0] == "diff":
			return diffOut, nil
		}
		return "", nil
	}

	failed, out := checkTestPresence(context.Background(), ws, runner)
	if !failed || !strings.Contains(out, "DiffNameOnly") {
		t.Fatalf("want failure naming DiffNameOnly, got failed=%v out=%q", failed, out)
	}
}

func TestNeuterChangedFuncs(t *testing.T) {
	src := "package x\n\n" +
		"import \"errors\"\n\n" +
		"func Untouched() error { return errors.New(\"keep\") }\n\n" +
		"func Changed() int { return 41 }\n"
	// pretend the diff changed only the Changed() func (line 7 of the new file)
	changedLines := map[int]bool{7: true}
	out, neutered, err := neuterFuncsInSource("x.go", []byte(src), changedLines)
	if err != nil {
		t.Fatal(err)
	}
	if len(neutered) != 1 || neutered[0] != "Changed" {
		t.Fatalf("neutered funcs = %v, want [Changed]", neutered)
	}
	s := string(out)
	if !strings.Contains(s, `panic("mutation-gate`) {
		t.Errorf("Changed body should be replaced with a panic; got:\n%s", s)
	}
	if !strings.Contains(s, `errors.New("keep")`) {
		t.Errorf("Untouched func must be preserved; got:\n%s", s)
	}
}

func TestCheckMutationSurvival_FlagsSurvivor(t *testing.T) {
	ws := t.TempDir()
	pkg := filepath.Join(ws, "pkg/x")
	_ = os.MkdirAll(pkg, 0o755)
	_ = os.WriteFile(filepath.Join(pkg, "x.go"),
		[]byte("package x\n\nfunc Add(a, b int) int { return a + b }\n"), 0o644)
	_ = os.WriteFile(filepath.Join(pkg, "x_test.go"),
		[]byte("package x\n\nimport \"testing\"\n\nfunc TestAdd(t *testing.T){ _ = Add }\n"), 0o644)

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return " M pkg/x/x.go\x00 M pkg/x/x_test.go\x00", nil
		case name == "git" && args[0] == "diff":
			return "@@ -0,0 +3 @@\n+func Add(a, b int) int { return a + b }\n", nil
		case name == "go" && args[0] == "test":
			return "ok", nil // weak test passes even with the body neutered -> SURVIVOR
		}
		return "", nil
	}
	failed, out := checkMutationSurvival(context.Background(), ws, runner)
	if !failed {
		t.Fatal("expected a survivor: weak test passes against neutered Add")
	}
	if !strings.Contains(out, "pkg/x") || !strings.Contains(out, "Add") {
		t.Errorf("feedback must name the package and surviving func; got:\n%s", out)
	}
}

func TestCheckMutationSurvival_PassesWhenTestsBite(t *testing.T) {
	ws := t.TempDir()
	pkg := filepath.Join(ws, "pkg/x")
	_ = os.MkdirAll(pkg, 0o755)
	orig := "package x\n\nfunc Add(a, b int) int { return a + b }\n"
	_ = os.WriteFile(filepath.Join(pkg, "x.go"), []byte(orig), 0o644)
	_ = os.WriteFile(filepath.Join(pkg, "x_test.go"), []byte("package x\n"), 0o644)

	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		switch {
		case name == "git" && args[0] == "status":
			return " M pkg/x/x.go\x00 M pkg/x/x_test.go\x00", nil
		case name == "git" && args[0] == "diff":
			return "@@ -0,0 +3 @@\n+func Add(a, b int) int { return a + b }\n", nil
		case name == "go" && args[0] == "test":
			return "FAIL", context.DeadlineExceeded // non-nil -> tests failed under neuter -> they bite
		}
		return "", nil
	}
	failed, _ := checkMutationSurvival(context.Background(), ws, runner)
	if failed {
		t.Fatal("must pass: tests fail under neuter (they bite)")
	}
	got, _ := os.ReadFile(filepath.Join(pkg, "x.go"))
	if string(got) != orig {
		t.Fatalf("x.go not restored; got:\n%s", got)
	}
}

// TestNeuterAndTestPackage_RealGoTest exercises the AST rewrite + a real
// `go test`: it copies the weak-test fixture module into a temp dir, neuters
// Add's body, and confirms the weak test still passes (a true survivor),
// proving the neutered source compiles and the survival signal is real.
func TestNeuterAndTestPackage_RealGoTest(t *testing.T) {
	ws := t.TempDir()
	copyTree(t, "testdata/mutation/weak", filepath.Join(ws, "weak"))

	orig, err := os.ReadFile(filepath.Join(ws, "weak/calc.go"))
	if err != nil {
		t.Fatal(err)
	}
	neutered, names, err := neuterFuncsInSource("calc.go", orig, map[int]bool{3: true})
	if err != nil || len(names) != 1 || names[0] != "Add" {
		t.Fatalf("neuter failed: err=%v names=%v", err, names)
	}
	if err := os.WriteFile(filepath.Join(ws, "weak/calc.go"), neutered, 0o644); err != nil {
		t.Fatal(err)
	}
	weakDir := filepath.Join(ws, "weak")
	if _, err := execCommandRunner(context.Background(), weakDir, nil, "go", "test", "./..."); err != nil {
		t.Fatalf("weak test should PASS under neuter (survivor), got err: %v", err)
	}
}

// copyTree copies a flat directory of files (test helper).
func copyTree(t *testing.T, src, dst string) {
	t.Helper()
	entries, err := os.ReadDir(src)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		data, err := os.ReadFile(filepath.Join(src, e.Name()))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dst, e.Name()), data, 0o644); err != nil {
			t.Fatal(err)
		}
	}
}
