/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package agent

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func TestIsGeneratedGoFile(t *testing.T) {
	ws := t.TempDir()
	write := func(rel, content string) {
		full := filepath.Join(ws, rel)
		_ = os.MkdirAll(filepath.Dir(full), 0o755)
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("api/zz_generated.deepcopy.go", "package v1\n")
	write("pkg/x/thing.pb.go", "package x\n")
	write("pkg/x/gen.go", "// Code generated by foo. DO NOT EDIT.\npackage x\n")
	write("pkg/x/hand.go", "package x\n\nfunc F() {}\n")

	cases := map[string]bool{
		"api/zz_generated.deepcopy.go": true,
		"pkg/x/thing.pb.go":            true,
		"pkg/x/gen.go":                 true,
		"pkg/x/hand.go":                false,
	}
	for path, want := range cases {
		if got := isGeneratedGoFile(ws, path); got != want {
			t.Errorf("isGeneratedGoFile(%q)=%v want %v", path, got, want)
		}
	}
}

func TestChangedNonTestGoFiles(t *testing.T) {
	ws := t.TempDir()
	for _, p := range []string{"pkg/x/hand.go", "pkg/x/hand_test.go", "pkg/x/zz_generated.deepcopy.go"} {
		full := filepath.Join(ws, p)
		_ = os.MkdirAll(filepath.Dir(full), 0o755)
		_ = os.WriteFile(full, []byte("package x\n"), 0o644)
	}
	runner := func(_ context.Context, _ string, _ []string, name string, args ...string) (string, error) {
		return " M pkg/x/hand.go\x00 M pkg/x/hand_test.go\x00 M pkg/x/zz_generated.deepcopy.go\x00 M docs/readme.md\x00", nil
	}
	got := changedNonTestGoFiles(context.Background(), ws, runner)
	if len(got) != 1 || got[0] != "pkg/x/hand.go" {
		t.Fatalf("changedNonTestGoFiles = %v, want [pkg/x/hand.go]", got)
	}
}
