#!/bin/bash
# Multi-GPU Quick Start Script for Azure AKS
# For testing Issue #2 - Multi-GPU single-node support

set -e

echo "🚀 LLMKube Multi-GPU Azure AKS Cluster Setup"
echo "============================================="
echo "This will create an AKS cluster with 2 GPUs per node for multi-GPU testing"
echo ""

# Check if az CLI is installed
if ! command -v az &> /dev/null; then
    echo "❌ Azure CLI not found. Installing..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew install azure-cli
    else
        echo "Please install Azure CLI: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
        exit 1
    fi
fi

# Check if terraform is installed
if ! command -v terraform &> /dev/null; then
    echo "❌ Terraform not found. Installing..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew install terraform
    else
        echo "Please install Terraform: https://www.terraform.io/downloads"
        exit 1
    fi
fi

# Check if kubectl is installed
if ! command -v kubectl &> /dev/null; then
    echo "❌ kubectl not found. Installing..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew install kubectl
    else
        echo "Please install kubectl: https://kubernetes.io/docs/tasks/tools/"
        exit 1
    fi
fi

# Check if authenticated
echo "🔐 Checking Azure authentication..."
if ! az account show &> /dev/null; then
    echo "Not authenticated. Logging in..."
    az login
fi

# Get or set subscription
CURRENT_SUB=$(az account show --query id -o tsv 2>/dev/null)
if [ -z "$CURRENT_SUB" ]; then
    echo ""
    echo "📋 Available subscriptions:"
    az account list --query "[].{Name:name, ID:id, State:state}" --output table
    echo ""
    read -p "Enter subscription ID: " SUB_ID
    az account set --subscription "$SUB_ID"
else
    SUB_ID=$CURRENT_SUB
    SUB_NAME=$(az account show --query name -o tsv)
    echo "✅ Using subscription: $SUB_NAME ($SUB_ID)"
fi

# Check GPU quota in West US 2
echo ""
echo "🔍 Checking GPU quota in West US 2..."
echo ""
echo "IMPORTANT: Azure requires quota requests for GPU VMs."
echo "Check your quota at: https://portal.azure.com > Subscriptions > Usage + quotas"
echo ""
echo "Required quotas for this deployment:"
echo "  - Standard NCv3 Family vCPUs: 12+ (for 2x V100)"
echo "  - Standard NCASv3_T4 Family vCPUs: 64+ (for 4x T4, if using T4 option)"
echo ""
read -p "Have you verified your GPU quota? (y/n): " QUOTA_OK
if [[ ! "$QUOTA_OK" =~ ^[Yy]$ ]]; then
    echo ""
    echo "⚠️  Please request GPU quota before proceeding:"
    echo "1. Go to: https://portal.azure.com"
    echo "2. Navigate to: Subscriptions > Usage + quotas"
    echo "3. Search for: 'Standard NCv3 Family vCPUs'"
    echo "4. Request quota increase to at least 12 vCPUs"
    echo "5. Approval typically takes 1-2 business days"
    echo ""
    read -p "Continue anyway? (y/n): " CONTINUE
    if [[ ! "$CONTINUE" =~ ^[Yy]$ ]]; then
        echo "Exiting. Please request quota first."
        exit 1
    fi
fi

# Ask user to select GPU type
echo ""
echo "🎮 Select GPU configuration:"
echo "  1) 2x V100 GPUs (Recommended - Standard_NC12s_v3, ~$0.90/hr spot)"
echo "  2) 4x T4 GPUs (will use 2 - Standard_NC64as_T4_v3, ~$1.20/hr spot)"
echo "  3) 2x A100 GPUs (Best performance - Standard_NC24ads_A100_v4, ~$2.50/hr spot)"
read -p "Choice (1, 2, or 3): " GPU_CHOICE

if [ "$GPU_CHOICE" == "3" ]; then
    GPU_VM_SIZE="Standard_NC24ads_A100_v4"
    GPU_NAME="A100"
    GPU_COUNT=2
elif [ "$GPU_CHOICE" == "2" ]; then
    GPU_VM_SIZE="Standard_NC64as_T4_v3"
    GPU_NAME="T4"
    GPU_COUNT=2
else
    GPU_VM_SIZE="Standard_NC12s_v3"
    GPU_NAME="V100"
    GPU_COUNT=2
fi

echo "✅ Selected: 2x $GPU_NAME GPUs ($GPU_VM_SIZE)"

# Ask about spot instances
echo ""
read -p "Use Azure Spot VMs for ~80% cost savings? (y/n): " USE_SPOT
if [[ "$USE_SPOT" =~ ^[Yy]$ ]]; then
    ENABLE_SPOT="true"
    SPOT_TEXT="spot"
else
    ENABLE_SPOT="false"
    SPOT_TEXT="on-demand"
fi

# Create terraform.tfvars
echo ""
echo "📝 Creating terraform.tfvars for multi-GPU configuration..."
cat > terraform.tfvars <<EOF
# Multi-GPU Configuration for LLMKube Testing (Issue #2)
# Auto-generated by multi-gpu-quick-start.sh

subscription_id     = "$SUB_ID"
resource_group_name = "llmkube-multi-gpu-rg"
cluster_name        = "llmkube-multi-gpu-test"
location            = "westus2"
kubernetes_version  = "1.31.13"

# Multi-GPU Configuration: 2 GPUs per node
gpu_vm_size = "$GPU_VM_SIZE"
gpu_count   = $GPU_COUNT

# Auto-scaling: Start at 0 to save money
min_gpu_nodes = 0
max_gpu_nodes = 2

# System nodes for Kubernetes
system_node_count = 1
system_vm_size    = "Standard_D2s_v3"

# Spot instances for cost savings
enable_spot    = $ENABLE_SPOT
spot_max_price = -1

# Disk size for models
disk_size_gb = 200

# Tags
tags = {
  project     = "llmkube"
  environment = "testing"
  purpose     = "multi-gpu-llm-inference"
  issue       = "2"
}
EOF

echo "✅ Configuration saved to terraform.tfvars"

# Initialize Terraform
echo ""
echo "🔧 Initializing Terraform..."
terraform init

# Validate configuration
echo ""
echo "✅ Validating Terraform configuration..."
terraform validate

# Show plan
echo ""
echo "📋 Terraform Plan:"
echo "===================="
terraform plan

# Confirm deployment
echo ""
echo "⚠️  Cost Estimate:"
case "$GPU_VM_SIZE" in
    "Standard_NC12s_v3")
        if [ "$ENABLE_SPOT" == "true" ]; then
            echo "  ~$0.90/hr per GPU node when running ($SPOT_TEXT)"
            echo "  ~$650/month if running 24/7"
        else
            echo "  ~$4.54/hr per GPU node when running ($SPOT_TEXT)"
            echo "  ~$3,270/month if running 24/7"
        fi
        ;;
    "Standard_NC64as_T4_v3")
        if [ "$ENABLE_SPOT" == "true" ]; then
            echo "  ~$1.20/hr per GPU node when running ($SPOT_TEXT)"
            echo "  ~$865/month if running 24/7"
        else
            echo "  ~$6.02/hr per GPU node when running ($SPOT_TEXT)"
            echo "  ~$4,340/month if running 24/7"
        fi
        ;;
    "Standard_NC24ads_A100_v4")
        if [ "$ENABLE_SPOT" == "true" ]; then
            echo "  ~$2.50/hr per GPU node when running ($SPOT_TEXT)"
            echo "  ~$1,800/month if running 24/7"
        else
            echo "  ~$12.50/hr per GPU node when running ($SPOT_TEXT)"
            echo "  ~$9,000/month if running 24/7"
        fi
        ;;
esac
echo ""
echo "  With auto-scale to 0: ~$50-200/month for testing"
echo "  System nodes: ~$70/month (always running)"
echo ""
echo "💡 Remember to run 'terraform destroy' when done testing!"
echo ""

read -p "Proceed with deployment? (y/n): " PROCEED
if [[ ! "$PROCEED" =~ ^[Yy]$ ]]; then
    echo "Deployment cancelled."
    exit 0
fi

# Deploy
echo ""
echo "🚀 Deploying AKS cluster with multi-GPU support..."
echo "This will take approximately 10-15 minutes..."
echo ""
terraform apply -auto-approve

# Get cluster credentials
echo ""
echo "🔑 Getting cluster credentials..."
eval $(terraform output -raw connect_command)

# Wait for cluster to be ready
echo ""
echo "⏳ Waiting for cluster to be ready..."
sleep 30

# Verify cluster
echo ""
echo "✅ Verifying cluster..."
kubectl get nodes

# Verify GPU device plugin
echo ""
echo "🔍 Checking NVIDIA device plugin..."
kubectl get pods -n kube-system -l name=nvidia-device-plugin-ds

# Check GPU allocation (may be 0 if no GPU nodes running yet due to autoscaling)
echo ""
echo "🎮 Checking GPU allocation..."
kubectl get nodes -o custom-columns=NAME:.metadata.name,GPU:.status.allocatable."nvidia\.com/gpu"

echo ""
echo "=================================================="
echo "✅ Multi-GPU AKS Cluster Deployed Successfully!"
echo "=================================================="
echo ""
echo "Cluster: $(terraform output -raw cluster_name)"
echo "Location: $(terraform output -raw cluster_location)"
echo "GPU VM Size: $(terraform output -raw gpu_vm_size)"
echo "Estimated Cost: $(terraform output -raw estimated_hourly_cost)"
echo ""
echo "Next steps:"
echo "1. Deploy a multi-GPU model:"
echo "   kubectl apply -f ../../config/samples/multi-gpu-llama-13b-model.yaml"
echo ""
echo "2. Monitor GPU nodes (will auto-scale from 0 when model is deployed):"
echo "   kubectl get nodes -w"
echo ""
echo "3. When done testing, destroy the cluster to save costs:"
echo "   terraform destroy"
echo ""
echo "📖 Full documentation: ../../MULTI-GPU-DEPLOYMENT.md"
echo ""
