#!/usr/bin/env bash
# check-helm-rbac.sh — guard against the Helm charts' RBAC drifting behind the
# kubebuilder-generated source of truth (#379, the RBAC analogue of the #367
# CRD sync guard).
#
# config/rbac/role.yaml is regenerated by `make manifests` from the
# kubebuilder:rbac markers and is the authoritative set of rules the operator
# binary needs. Those rules ship split across two hand-maintained charts whose
# ClusterRoles are NOT generated:
#
#   - charts/llmkube  (inference operator)
#   - charts/foreman  (foreman operator + agent)
#
# A new marker that lands in role.yaml but not in a chart silently breaks the
# in-cluster operator (the failure mode from PR #376: the binary had a new
# Endpoints lookup but the ClusterRole did not grant it, so the cache never
# synced). This check renders both charts and fails if any rule in role.yaml is
# NOT covered by the union of the chart RBAC. Extra chart rules (e.g.
# leader-election leases that kubebuilder emits into a separate role) are fine:
# the charts must be a SUPERSET of role.yaml, not an exact match.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ROLE="$REPO_ROOT/config/rbac/role.yaml"

command -v helm >/dev/null 2>&1 || { echo "❌ helm is required"; exit 2; }
python3 -c 'import yaml' >/dev/null 2>&1 || { echo "❌ python3 with PyYAML is required (pip install pyyaml)"; exit 2; }
[ -f "$ROLE" ] || { echo "❌ $ROLE not found (run 'make manifests' first)"; exit 2; }

render() {
  # Render only RBAC: enable rbac.create, skip CRDs to keep output small.
  helm template "$1" --set rbac.create=true --set crds.install=false 2>/dev/null || {
    echo "❌ helm template failed for $1" >&2
    exit 2
  }
}

CHART_RBAC="$(render "$REPO_ROOT/charts/llmkube"; echo '---'; render "$REPO_ROOT/charts/foreman")"

# Pass the rendered chart YAML to python via a temp FILE, not an env var.
# The full render can exceed the OS env+argv size limit on Linux (E2BIG /
# "Argument list too long"), e.g. once the foreman chart emits the webhook
# Secret + ValidatingWebhookConfiguration with their base64 cert blobs.
CHART_YAML_FILE="$(mktemp)"
trap 'rm -f "$CHART_YAML_FILE"' EXIT
printf '%s\n' "$CHART_RBAC" > "$CHART_YAML_FILE"

ROLE_YAML="$ROLE" CHART_YAML="$CHART_YAML_FILE" python3 - <<'PY'
import os, sys, yaml

def triples(text):
    """Every (apiGroup, resource, verb) granted by ClusterRole/Role docs."""
    out = set()
    for doc in yaml.safe_load_all(text):
        if not isinstance(doc, dict):
            continue
        if doc.get("kind") not in ("ClusterRole", "Role"):
            continue
        for rule in (doc.get("rules") or []):
            groups = rule.get("apiGroups") or [""]
            for g in groups:
                for r in (rule.get("resources") or []):
                    for v in (rule.get("verbs") or []):
                        out.add((g, r, v))
    return out

need = triples(open(os.environ["ROLE_YAML"]).read())
have = triples(open(os.environ["CHART_YAML"]).read())
missing = sorted(need - have)
if missing:
    print("❌ Helm RBAC is missing rules present in config/rbac/role.yaml:")
    for g, r, v in missing:
        print(f"     apiGroup={g or '(core)'} resource={r} verb={v}")
    print()
    print("The kubebuilder markers granted a permission the charts don't. Add it")
    print("to charts/llmkube/templates/clusterrole.yaml (inference operator) or")
    print("charts/foreman/templates/operator-rbac.yaml (foreman operator) to match.")
    sys.exit(1)
print(f"✅ Helm RBAC covers all {len(need)} kubebuilder rules "
      f"({len(have)} granted across the charts).")
PY
